"""add_priority_score_and_low_stock_threshold

Revision ID: f31e433e58db
Revises: 8d448a2a5227
Create Date: 2026-06-26 18:37:36.643302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f31e433e58db'
down_revision: Union[str, None] = '8d448a2a5227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('priority_score', sa.Numeric(precision=6, scale=2), nullable=True))
    op.create_index(op.f('ix_alerts_priority_score'), 'alerts', ['priority_score'], unique=False)
    op.add_column('inventory_items', sa.Column('priority_score', sa.Numeric(precision=6, scale=2), nullable=True))
    op.create_index(op.f('ix_inventory_items_priority_score'), 'inventory_items', ['priority_score'], unique=False)
    op.add_column('products', sa.Column('low_stock_threshold', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'low_stock_threshold')
    op.drop_index(op.f('ix_inventory_items_priority_score'), table_name='inventory_items')
    op.drop_column('inventory_items', 'priority_score')
    op.drop_index(op.f('ix_alerts_priority_score'), table_name='alerts')
    op.drop_column('alerts', 'priority_score')
    # ### end Alembic commands ###
